### ISSUE TITLE
Seems not to match properly.

### ISSUE THREAD

**Issue by MistressPlague** [aiqinxuancai/TiktokenSharp#10]
the test string: "Hello, world! This is an example. ttttt abc ddd" returns a total of 15 tokens with gpt 3.5 turbo on your lib, yet https://platform.openai.com/tokenizer shows 16. Why is this?

**Comment by MistressPlague** [comment]
Even the token ID's don't remotely match.
TiktokenSharp: 9906, 11, 1917, 0, 1115, 374, 459, 3187, 13, 259, 5683, 5683, 40122, 294, 634
OpenAI Officially: 15496, 11, 995, 0, 770, 318, 281, 1672, 13, 256, 926, 926, 450, 66, 288, 1860

**Comment by MistressPlague** [comment]
![image](https://github.com/aiqinxuancai/TiktokenSharp/assets/36628963/857c2158-b781-4b7b-abbb-838882465153)
100% confirmed, both this and SharpToken do not match at all. If they did, then me limiting messages in request to 2048 and the maxtokens for the response to 2048 would of worked. It didn't.

**Comment by aiqinxuancai** [comment]
Thank you for your feedback. 

After testing, the TiktokenSharp library works correctly with the "gpt-3.5-turbo" encoder, i.e. "cl100k_base", with both encoding and decoding being correct. The encoder you viewed on the page [https://platform.openai.com/tokenizer](https://platform.openai.com/tokenizer) is not "cl100k_base", and the page does not indicate that it is suitable for "gpt-3.5-turbo". In fact, after my testing, the encoder on the page is "p50k_base", which is suitable for models such as "text-davinci-003". 

As for the error you encountered in your actual application, I think it is not directly related to this library. The prompt has clearly indicated that the number of tokens you requested plus the number of tokens returned exceeds the model limit of 4097. I believe you can solve this problem.

**Comment by MistressPlague** [comment]
The error was from the prompt being too many tokens, yet this library was used with cl100k_base to count them and have it be at the cap, and it counted the tokens wrong. I tested both each ChatMessage content individually, and all of them as one string. Both of which gave incorrect token counts.

**Comment by aiqinxuancai** [comment]
> 

This is clearly a problem with using the OpenAI API interface, which is not directly related to this library. This library is only responsible for correctly counting the number of tokens. 

Although your problem is not within the scope of this library, I can remind you that the token calculation method in the API interface is not only based on the content sent and received, but also includes the "user" and "assistant" labels. For specific implementation, I suggest you refer to some third-party implementations, such as: https://github.com/waylaidwanderer/node-chatgpt-api/blob/main/src/ChatGPTClient.js#L479C28-L479C28, or I suggest you directly use some third-party C# libraries for chatGPT to implement the functionality.
