### ISSUE TITLE
TikToken.EncodingForModel("gpt-3.5-turbo") hangs when context is a WPF appplication.

### ISSUE THREAD

**Issue by felipedrumond** [aiqinxuancai/TiktokenSharp#11]
I have a library that uses TikToken  with:
` TikToken tikToken = TikToken.EncodingForModel("gpt-3.5-turbo")`;

When using that library in a WPF application, this code will hang forever even after getting a 200 http status when fetching 
https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken (I used Fiddler to find this out).

Using my same library in a Console context doesn't hang. 
1) what can be happening in the WPF context?
2) is there a way to bypass the download of cl100k_base.tiktoken all the time?

Obs.: I copied cl100k_base.tiktoken file to bin\Debug\net7.0-windows\bpe folder  in my compiled project and bypassed this problem.

**Comment by aiqinxuancai** [comment]
Since EncodingForModel is a synchronous method, this will block the thread. If you want to use this method, it should run asynchronously in Task. You can also use the asynchronous method EncodingForModelAsync.

I checked the code that downloads the cl100k_base.tiktoken file and found nothing wrong. When deploying in a production environment, I recommend packaging the cl100k_base.tiktoken file directly to avoid occasional network issues.
