### ISSUE TITLE
Add support for gpt-4-turbo (preview) models

### ISSUE THREAD

**Issue by hempels** [aiqinxuancai/TiktokenSharp#18]
The solution for mapping model names to encodings is problematic because it forces exact matches and can't easily be kept up to date. It would be more robust to allow for classes of models, for instance all chat completion models encode using cl100k_base, regardless of which specific model is selected.

As of this message, these are just the currently supported gpt-4 chat completion model names from OpenAI:
gpt-4-0125-preview
gpt-4-turbo-preview
gpt-4-1106-preview
gpt-4
gpt-4-0613
gpt-4-0314
gpt-4-32k
gpt-4-32k-0613

The first three are not presently supported by this library.

**Comment by aiqinxuancai** [comment]
In the code in this repository, there is a fuzzy matching implemented, and all models starting with "gpt-4" can correctly obtain the cl100k_base encoder. Although model names such as "gpt-4-0125-preview" are not directly included in the code, they are actually available.

Of course, if OpenAI publish model gpt-5, this repository will need to be updated in order to use the EncodingForModel method. If you find that some models cannot obtain the encoder, you can use TikToken.GetEncoding() to get the encoder you need, or you can provide feedback here.

**Comment by hempels** [comment]
To be clear, you're saying the fuzzy matching is in the repo but is not yet included in a nuget release? Or it should be available in the latest release?

**Comment by aiqinxuancai** [comment]
> To be clear, you're saying the fuzzy matching is in the repo but is not yet included in a nuget release? Or it should be available in the latest release?

Use nuget version 1.0.9 test.
![image](https://github.com/aiqinxuancai/TiktokenSharp/assets/4475018/258e3be5-2dab-4388-ad37-bdce69dcf0c8)
